files:
  - source: src/main/generated/assets/mint/lang/*.json
    translation: /src/main/resources/assets/mint/lang/%locale_with_underscore%.%file_extension%
  - source: /src/main/resources/assets/*/lang/*.json
    translation: '%original_path%/%locale_with_underscore%.%file_extension%'
